### ISSUE TITLE
[Bug report] Memory branch

### ISSUE THREAD

**Issue by seungjun-Park** [SWTube/Darkest-Cave#18]
Reproduction Steps
1. memory 브렌치 사본으로 이동한다.
2. 빌드한다.

Real Result
1. 빌드가 되지 않는다.

Expected Result
1. 빌드가 되는 것

Build Infomation
Branch: memory
Commit:
Log Message: 
설명/ 프로젝트/ 파일/ 줄

1. = 함수오버로드를 확인할 수 없습니다/ CaveEngine/ String.ixx/ 211, 242, 270, 410, 483, 

2. cave::String::mCapactiy 멤버를 초기화할 수 없습니다/ String.ixx/ 138

3. GetSufficientCapacity 식별자를 찾을 수 없습니다/ CaveEngine/ Memory.h/ 19

4. size_t cave:GetSufficientCapacity(size_t) 함수 템플릿이 이미 정의되었습니다/ CaveEngine/ String.ixx/ 16

5. 초기화 중 size_t(__cdecl*)(size_t)에서 size_t로 변환할 수 없습니다/ CaveEngine/ String.ixx/ 136, 758, 1788

**Comment by seungjun-Park** [comment]
오류코드는 순서대로 C2568, C2439, C3861, C2995, C2440

**Comment by Alegruz** [comment]
please merge the lastest commit of  "develop_team/core_team"

the issue has been taken care

the duplicate function "`GetSufficientCapacity`" was removed from String.ixx for it has been moved to "Memory.h"

**Comment by seungjun-Park** [comment]
오류코드/ 설명/ 프로젝트/ 파일/ 줄
1. C2039/ cout: std의 멤버가 아닙니다/ CaveEngine/ TStack.h/ 485, 500, 504
2. C2572/ std::basic_istream: 기본 인수 재정의. 매개변수 2/ CaveEngine/ iosfwd/ 179, 181
3. C1038/ 소스 파일을 열 수 없습니다. 'Core\Private\Memory\Allocator.cpp': No such file or directory./ CaveEngine/ c1xx/ 1

**Comment by Alegruz** [comment]
following issues are taken care of.

please remerge develop_team/core_team branch

**Comment by seungjun-Park** [comment]
2, 3번 오류 고쳐지지 않음. 
1. E0020/ 식별자 LOGD가 정의되어 있지 않습니다/ CaveEngine/ MemoryPool.cpp/ 190, 196
2. E0135/ namespace std에 cout 멤버가 없습니다/ CaveEngine/ MemoryPool.cpp/ 190, 196
3. C3861/ LOGD 식별자를 찾을 수 없습니다/ CaveEngine/ MemoryPool.cpp/ 190, 196
4. C2653/ eLogChannel 클래스 또는 네임스페이스 이름이 아닙니다./ CaveEngine/ MemoryPool.cpp/ 190, 196
5. C2065/ cout 선언되지 않은 식별자입니다./ CaveEngine/ MomryPool.cpp/ 190,196
6. C2039/ cout std의 멤버가 아닙니다./ CaveEngine/ MemoryPool.cpp/ 190, 196
7. CORE_MEMORY 선언되지 않은 식별자 입니다./ CaveEngine/ MemoryPool.cpp/ 190, 196
8. E0276/ ::가 뒤에 오는 이름은 클래스 또는 네임스페이스 이름이어야 합니다./ CaveEngine/ MemoryPool.cpp/ 190, 196

**Comment by Alegruz** [comment]
Log is now included in MemoryPool
