### ISSUE TITLE
[Bug report] core_team error

### ISSUE THREAD

**Issue by seungjun-Park** [SWTube/Darkest-Cave#33]
Reproduction Steps :
core_team 브렌치 사본으로 이동한다.
빌드한다.

Real Result :
빌드가 되지 않는다.

Expected Result :
빌드가 되는 것

Build Infomation
Branch: core_team
Commit:
Log Message:
설명/ 프로젝트/ 파일/ 줄
LNK1104/ Core.lib 파일을 열 수 없습니다./ Cave Engine/ LINK/ 1

**Comment by Alegruz** [comment]
임시 해결 방법 -> CaveEngine 속성 -> Linker > Input에서 Core.lib 삭제

**Comment by Alegruz** [comment]
+추가)

CaveEngine 속성 -> Post Build Event에서 xcopy 명령어 제거
